import Head from 'next/head';
import styles from '@/styles/Home.module.scss';

export default function Home() {
  const numArray = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  const evenNums = numArray.filter((num) => num % 2 === 0);

  return (
    <>
      <Head>
        <title>Reddit Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Hello World</h1>
        <h2>Even Numbers</h2>
        <ul>
          {evenNums.map((num) => (
            <li key={num}>{num}</li>
          ))}
        </ul>
      </main>
    </>
  );
}
